In [2]:
pip install tensorflow

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [3]:
from tensorflow.keras.preprocessing.text import one_hot

In [14]:
#sentences
sent = ['i am a rajesh',
        'my name is rajesh',
        'i am a datascientist',
        'iam a good datascientist',
        'a cup of tea',
        'similiar words of word']

In [15]:
sent

['i am a rajesh',
 'my name is rajesh',
 'i am a datascientist',
 'iam a good datascientist',
 'a cup of tea',
 'similiar words of word']

In [6]:
#vocab size
voc_size = 10000

# One Hot Encoding

In [8]:
onehot_rep= [one_hot(words,voc_size)for words in sent]
print(onehot_rep)

[[3999, 1645], [7592, 2581, 5637, 1645], [3999, 7018, 1734], [3999, 7018, 5506, 1734], [5550, 8531, 4967], [4106, 5455, 8531, 5660]]


# Word Embedding Represntation

In [10]:
import tensorflow

In [12]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [13]:
import numpy as np

In [16]:
sent_length = 8
embedded_docs = pad_sequences(onehot_rep, padding = 'pre',maxlen =sent_length)
print(embedded_docs)

[[   0    0    0    0    0    0 3999 1645]
 [   0    0    0    0 7592 2581 5637 1645]
 [   0    0    0    0    0 3999 7018 1734]
 [   0    0    0    0 3999 7018 5506 1734]
 [   0    0    0    0    0 5550 8531 4967]
 [   0    0    0    0 4106 5455 8531 5660]]


In [17]:
dim = 10

In [18]:
model = Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [19]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [21]:
print(model.predict(embedded_docs))

[[[-0.04685029  0.03374593 -0.03022604  0.02569017 -0.02046477
   -0.00512093  0.00261103  0.01615263  0.03050287 -0.00194774]
  [-0.04685029  0.03374593 -0.03022604  0.02569017 -0.02046477
   -0.00512093  0.00261103  0.01615263  0.03050287 -0.00194774]
  [-0.04685029  0.03374593 -0.03022604  0.02569017 -0.02046477
   -0.00512093  0.00261103  0.01615263  0.03050287 -0.00194774]
  [-0.04685029  0.03374593 -0.03022604  0.02569017 -0.02046477
   -0.00512093  0.00261103  0.01615263  0.03050287 -0.00194774]
  [-0.04685029  0.03374593 -0.03022604  0.02569017 -0.02046477
   -0.00512093  0.00261103  0.01615263  0.03050287 -0.00194774]
  [-0.04685029  0.03374593 -0.03022604  0.02569017 -0.02046477
   -0.00512093  0.00261103  0.01615263  0.03050287 -0.00194774]
  [ 0.0184367   0.02601366  0.01529379  0.01152904  0.02634238
    0.01641648 -0.01224066 -0.04297024 -0.03545346 -0.01068182]
  [-0.03086606 -0.03040272 -0.04961717  0.00231234 -0.00151319
    0.0239122   0.02126471  0.0186926   0.002461

In [22]:
embedded_docs[0]

array([   0,    0,    0,    0,    0,    0, 3999, 1645], dtype=int32)

In [23]:
print9=(model.predict(embedded_docs)[0])